[package]
name = "rwatch"
version = "0.1.0"
edition = "2018"

[dependencies]
clap = "3.0.0" # check for the latest version
crossterm = "0.26.0" # check for the latest version
ctrlc = "3.1.9" # check for the latest version
